const state={route:'home',history:[],selectedCrop:'tomato',harvestCount:3,tasks:JSON.parse(localStorage.getItem('tanyV7Tasks')||'[]'),journal:JSON.parse(localStorage.getItem('tanyV7Journal')||'[]')};
const crops={tomato:{name:'ミニトマト',variety:'アイコ',emoji:'🍅',status:'収穫中',progress:72,place:'3畝目'},watermelon:{name:'小玉スイカ',variety:'品種不明',emoji:'🍉',status:'生育中',progress:58,place:'2畝目'},pepper:{name:'ピーマン',variety:'京みどり',emoji:'🫑',status:'収穫中',progress:67,place:'4畝目'},basil:{name:'バジル',variety:'スイートバジル',emoji:'🌿',status:'生育中',progress:46,place:'1・3・4畝目'},shiso:{name:'青じそ',variety:'青じそ',emoji:'🌱',status:'収穫中',progress:61,place:'1畝目'},kushinsai:{name:'空芯菜',variety:'空芯菜',emoji:'🥬',status:'生育中',progress:44,place:'5畝目'}};
const suggestions=[
{id:'s1',title:'スイカの実と保護カゴを確認',reason:'前回の確認から3日。食害と接地面を見ましょう。'},
{id:'s2',title:'乾いている株だけ水やり',reason:'晴れ予報ですが、土と葉の状態で判断しましょう。'}];
const $=s=>document.querySelector(s),main=$('#main'),header=$('#appHeader'),tabbar=$('#tabbar');
function mascot(cls=''){return `<div class="mascot-v6 ${cls}" aria-label="tany仮キャラクター"><svg viewBox="0 0 120 120"><path d="M58 34 C50 18 34 14 23 22 C31 37 43 43 58 42" fill="#6f9168"/><path d="M61 33 C68 16 84 13 97 22 C90 37 76 43 61 42" fill="#86a978"/><path d="M60 39 C61 31 62 25 66 18" stroke="#55705a" stroke-width="5" stroke-linecap="round"/><circle cx="60" cy="70" r="35" fill="#fff9ec" stroke="#d9cdbb" stroke-width="3"/><circle cx="48" cy="67" r="4" fill="#4b4339"/><circle cx="72" cy="67" r="4" fill="#4b4339"/><path d="M48 81 Q60 91 72 81" fill="none" stroke="#4b4339" stroke-width="4" stroke-linecap="round"/></svg><span>仮キャラ</span></div>`}
function init(){setTimeout(()=>{$('#splash').style.opacity=0;setTimeout(()=>$('#splash').remove(),300);header.classList.remove('hidden');main.classList.remove('hidden');tabbar.classList.remove('hidden');render()},500);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>navigate(b.dataset.tab,true));$('#settingsButton').onclick=()=>navigate('settings');$('#backButton').onclick=goBack}
function navigate(route,root=false,data){if(!root)state.history.push(state.route);else state.history=[];state.route=route;if(data)Object.assign(state,data);scrollTo(0,0);render()}
function goBack(){state.route=state.history.pop()||'home';render()}
function titleFor(r){return({home:'Home',crops:'栽培',cropDetail:'栽培詳細',harvest:'収穫入力',footprint:'足あと',journal:'日誌',journalDetail:'日誌詳細',library:'図鑑',settings:'設定',taskEdit:'作業を編集'})[r]}
function render(){const root=['home','crops','journal','library'].includes(state.route);$('#pageTitle').textContent=titleFor(state.route);$('#backButton').classList.toggle('hidden',root);$('#settingsButton').classList.toggle('hidden',state.route!=='home');tabbar.classList.toggle('hidden',!root);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.route));({home:renderHome,crops:renderCrops,cropDetail:renderCropDetail,harvest:renderHarvest,footprint:renderFootprint,journal:renderJournal,journalDetail:renderJournalDetail,library:renderLibrary,settings:renderSettings,taskEdit:renderTaskEdit})[state.route]()}
function renderHome(){const adopted=state.tasks.filter(t=>t.status==='today');main.innerHTML=`<section class="review-banner"><b>v7 レビュー版</b><span>妻レビュー反映</span></section><section class="greeting"><h2>おはようございます</h2><p>今日の作業は、提案を見て自分たちで決めます。</p></section><section class="card tany-card"><div class="tany-head">${mascot()}<div class="tany-copy"><span class="badge">tanyから</span><h2>朝の涼しいうちに収穫しよう</h2><p>天気と栽培記録を参考にした提案です。採用するかは自分たちで決められます。</p></div></div><div class="today-status"><div class="status-pill"><b>晴れ・31℃</b><span>デモ天気</span></div><div class="status-pill"><b>収穫 4種</b><span>選択可能</span></div><div class="status-pill"><b>今日 ${adopted.length}件</b><span>自分で管理</span></div></div></section><button id="quickHarvest" class="quick-action"><span class="qa-icon">収</span><span><strong>収穫を記録する</strong><small>作物を選んで約30秒</small></span><span class="arrow">›</span></button><div class="section-head"><h2>tanyの提案</h2><span class="tiny muted">未確定</span></div><section class="suggestion-list">${suggestions.map(s=>`<article class="card suggestion-card"><div><span class="ai-label">提案・未保存</span><h3>${s.title}</h3><p>${s.reason}</p></div><div class="suggestion-actions"><button class="ghost small-btn" data-skip="${s.id}">今回はしない</button><button class="ghost small-btn" data-edit="${s.id}">編集</button><button class="primary small-btn" data-adopt="${s.id}">今日やる</button></div></article>`).join('')}</section><div class="section-head"><h2>今日やること</h2><button id="addTask" class="text-button">＋追加</button></div><section class="card task-card">${adopted.length?adopted.map((t,i)=>`<label class="task"><input type="checkbox" data-done="${i}" ${t.done?'checked':''}><span><strong>${t.title}</strong><span>${t.note||'自分たちで決めた作業'}</span></span><button class="task-edit" data-taskedit="${i}">編集</button></label>`).join(''):'<p class="muted tiny empty-note">まだありません。提案を採用するか、自分で追加できます。</p>'}</section><div class="section-head"><h2>今日の一枚</h2><span class="tiny muted">実写真に置換予定</span></div><section class="hero-photo"><div><strong>実際の農園写真が入ります</strong><p>撮影・選択した写真が日誌と栽培詳細に反映されます。</p><span class="version-chip">写真はデモ表示</span></div></section>`;
$('#quickHarvest').onclick=()=>navigate('harvest');$('#addTask').onclick=()=>navigate('taskEdit',false,{editingTask:null});main.querySelectorAll('[data-adopt]').forEach(b=>b.onclick=()=>{const s=suggestions.find(x=>x.id===b.dataset.adopt);state.tasks.push({title:s.title,note:s.reason,status:'today',done:false});saveTasks();renderHome();toast('「今日やること」に追加しました')});main.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>toast('今回は見送りました'));main.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const s=suggestions.find(x=>x.id===b.dataset.edit);navigate('taskEdit',false,{editingTask:{title:s.title,note:s.reason,index:null}})});main.querySelectorAll('[data-done]').forEach((el)=>el.onchange=()=>{adopted[+el.dataset.done].done=el.checked;saveTasks();renderHome()});main.querySelectorAll('[data-taskedit]').forEach(b=>b.onclick=e=>{e.preventDefault();navigate('taskEdit',false,{editingTask:{...adopted[+b.dataset.taskedit],index:state.tasks.indexOf(adopted[+b.dataset.taskedit])}})})}
function saveTasks(){localStorage.setItem('tanyV7Tasks',JSON.stringify(state.tasks))}
function renderTaskEdit(){const t=state.editingTask||{title:'',note:'',index:null};main.innerHTML=`<section class="card"><h2>${t.index===null?'作業を追加・調整':'作業を編集'}</h2><div class="form-group"><label>作業名</label><input id="taskTitle" value="${t.title||''}" placeholder="例：ピーマンを収穫"></div><div class="form-group"><label>判断メモ</label><textarea id="taskNote" placeholder="理由や注意点">${t.note||''}</textarea></div><p class="notice">tanyの提案をそのまま保存せず、内容を確認・編集してから「今日やること」に追加します。</p></section><div class="modal-actions"><button id="saveTask" class="primary full">今日やることに保存</button></div>`;$('#saveTask').onclick=()=>{const item={title:$('#taskTitle').value.trim()||'名称未設定の作業',note:$('#taskNote').value.trim(),status:'today',done:false};if(t.index===null)state.tasks.push(item);else state.tasks[t.index]={...state.tasks[t.index],...item};saveTasks();navigate('home',true);toast('作業を保存しました')}}
function renderCrops(){main.innerHTML=`<p class="muted tiny">写真部分は、完成版では登録した実際の写真になります。</p><div class="crop-grid">${Object.entries(crops).map(([id,c])=>`<button class="crop-card" data-crop="${id}"><div class="crop-photo">${c.emoji}<span class="photo-label">実写真予定</span></div><div class="crop-body"><span class="badge">${c.status}</span><h3>${c.name}</h3><p>${c.variety}</p><div class="progress"><i style="width:${c.progress}%"></i></div><div class="progress-label"><span>栽培の循環</span><span>${c.progress}%</span></div></div></button>`).join('')}</div>`;main.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>navigate('cropDetail',false,{selectedCrop:b.dataset.crop}))}
function renderCropDetail(){const c=crops[state.selectedCrop];main.innerHTML=`<section class="card detail-hero"><div class="detail-emoji">${c.emoji}</div><span class="badge">${c.status}</span><h2>${c.name}</h2><p>${c.variety}・${c.place}</p></section><section class="card"><h2>写真記録</h2><div class="photo-placeholder">📷<strong>実際の写真がここに並びます</strong><span>日誌と共通で利用</span></div></section><section class="card ai-suggestion"><div class="ai-label">tanyの提案・未保存</div><p>株の状態を確認し、必要なら作業に採用してください。</p><button class="ghost full" id="adoptCropTask">内容を確認して採用</button></section><button id="addHarvest" class="primary full">＋ 収穫を記録</button>`;$('#addHarvest').onclick=()=>navigate('harvest');$('#adoptCropTask').onclick=()=>navigate('taskEdit',false,{editingTask:{title:`${c.name}の状態を確認`,note:'提案内容を確認して採用',index:null}})}
function renderHarvest(){main.innerHTML=`<section class="card"><h2>収穫する作物を選ぶ</h2><div class="harvest-crop-list">${Object.entries(crops).filter(([id])=>['tomato','pepper','basil','shiso','kushinsai'].includes(id)).map(([id,c])=>`<button class="harvest-crop ${state.selectedCrop===id?'selected':''}" data-hcrop="${id}"><span>${c.emoji}</span><strong>${c.name}</strong></button>`).join('')}</div><div class="counter"><button id="minus">−</button><strong id="count">${state.harvestCount}</strong><button id="plus">＋</button></div><div class="form-group"><label>写真（任意）</label><button id="photoBtn" class="ghost full">📷 写真を撮る・選ぶ</button></div><div class="form-group"><label>メモ（任意）</label><input id="harvestMemo" placeholder="例：よく熟していた"></div></section><div class="modal-actions"><button id="saveHarvest" class="primary full">収穫を保存</button></div>`;main.querySelectorAll('[data-hcrop]').forEach(b=>b.onclick=()=>{state.selectedCrop=b.dataset.hcrop;renderHarvest()});$('#minus').onclick=()=>{$('#count').textContent=state.harvestCount=Math.max(0,state.harvestCount-1)};$('#plus').onclick=()=>{$('#count').textContent=++state.harvestCount};$('#photoBtn').onclick=()=>toast('完成版ではカメラ・写真選択を開きます');$('#saveHarvest').onclick=()=>{state.journal.unshift({id:Date.now(),crop:state.selectedCrop,count:state.harvestCount,memo:$('#harvestMemo').value||'',date:'7月21日',photo:true});localStorage.setItem('tanyV7Journal',JSON.stringify(state.journal));navigate('footprint')}}
function renderFootprint(){main.innerHTML=`<section class="card"><div class="tany-head">${mascot('small')}<div><h2>足あとを添えますか？</h2><p class="tiny muted">任意です。収穫記録はすでに保存されています。</p></div></div><div class="form-group"><label>一言</label><textarea id="footText" placeholder="例：妻と一緒に収穫できた"></textarea></div></section><div class="button-row modal-actions"><button id="skipFoot" class="ghost">追加しない</button><button id="saveFoot" class="primary">保存</button></div>`;$('#skipFoot').onclick=()=>navigate('journal',true);$('#saveFoot').onclick=()=>{if(state.journal[0])state.journal[0].footprint=$('#footText').value;localStorage.setItem('tanyV7Journal',JSON.stringify(state.journal));navigate('journal',true)}}
function renderJournal(){const demo=[{id:'d1',date:'7月21日',title:'朝の収穫と見回り',photo:true,body:'トマトとピーマンを収穫。スイカの保護カゴも確認。'},{id:'d2',date:'7月17日',title:'夏野菜の収穫',photo:true,body:'トマト6個、ピーマン2個、バジル、しそ。'}];const rows=[...state.journal,...demo];main.innerHTML=`<div class="section-head"><h2>農園の日誌</h2><button class="text-button" id="newJournal">＋記録</button></div><p class="muted tiny">タップすると詳細を開けます。写真は完成版で実際の写真になります。</p><div class="journal-list">${rows.map((r,i)=>`<button class="card journal-item" data-journal="${i}"><div class="journal-thumb">${r.photo?'📷':'📝'}</div><div><span class="tiny muted">${r.date}</span><h3>${r.title||`${crops[r.crop]?.name||'作物'}を${r.count}収穫`}</h3><p>${r.body||r.memo||'収穫を記録しました'}</p></div><span>›</span></button>`).join('')}</div>`;main.querySelectorAll('[data-journal]').forEach(b=>b.onclick=()=>navigate('journalDetail',false,{selectedJournal:rows[+b.dataset.journal]}));$('#newJournal').onclick=()=>toast('完成版では新しい日誌を作成できます')}
function renderJournalDetail(){const r=state.selectedJournal;main.innerHTML=`<section class="card"><span class="tiny muted">${r.date}</span><h2>${r.title||'収穫記録'}</h2><div class="photo-placeholder large">📷<strong>実際の写真</strong><span>デモでは仮表示です</span></div><p>${r.body||r.memo||'収穫を記録しました。'}</p><button class="ghost full" id="editJournal">この記録を編集</button></section>`;$('#editJournal').onclick=()=>toast('編集機能は次段階で接続します')}
function renderLibrary(){main.innerHTML=`<p class="muted tiny">作物ごとの知識と、自分たちの栽培記録を確認します。</p><section class="card"><h2>準備中</h2><p>図鑑は次の開発段階で検索・作物別ページを追加します。</p></section>`}
function renderSettings(){main.innerHTML=`<section class="card"><h2>表示と案内役</h2><div class="setting-row"><div><strong>tanyキャラクター</strong><span>正式イラストへいつでも差し替え可能</span></div><div class="toggle on"></div></div><div class="setting-row"><div><strong>天気連携</strong><span>現在は固定のデモデータ</span></div><div class="toggle"></div></div></section><section class="card"><h2>v7について</h2><p class="tiny muted">AI提案と正式保存を分離し、本人が採用・編集・見送りを判断するレビュー版です。</p></section>`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
