const STORAGE={records:'tanyV9Records',todos:'tanyV9Todos'};
const defaultRecords=[
  {id:1,date:'7月21日',iso:'2026-07-21',crop:'tomato',types:['harvest','photo'],count:6,memo:'赤く熟した実を収穫。甘みが増してきた。',photo:''},
  {id:2,date:'7月20日',iso:'2026-07-20',crop:'watermelon',types:['observe'],count:0,memo:'保護カゴの中で順調。つるも元気。',photo:''},
  {id:3,date:'7月17日',iso:'2026-07-17',crop:'pepper',types:['harvest'],count:2,memo:'小ぶりだが艶のよい実。',photo:''}
];
const crops={
 tomato:{name:'ミニトマト',variety:'アイコ',emoji:'🍅',place:'3畝目',stage:'収穫期',progress:82,outlook:'あと2週間ほど収穫見込み',caution:'実割れと葉の蒸れに注意',harvest:38,unit:'個'},
 watermelon:{name:'小玉スイカ',variety:'品種不明',emoji:'🍉',place:'2畝目',stage:'実を育てる時期',progress:68,outlook:'収穫まであと約1週間',caution:'食害と接地面を毎回確認',harvest:0,unit:'玉'},
 pepper:{name:'ピーマン',variety:'品種未登録',emoji:'🫑',place:'4畝目',stage:'収穫期',progress:76,outlook:'秋口まで収穫できる見込み',caution:'葉色と水切れを確認',harvest:14,unit:'個'},
 basil:{name:'バジル',variety:'スイートバジル',emoji:'🌿',place:'1・3・4畝目',stage:'収穫期',progress:72,outlook:'摘心しながら長く楽しめます',caution:'花芽は早めに摘む',harvest:9,unit:'回'},
 shiso:{name:'青じそ',variety:'青じそ',emoji:'🌱',place:'1畝目',stage:'収穫期',progress:70,outlook:'大きな葉から継続収穫',caution:'硬くなる前に収穫',harvest:7,unit:'回'},
 kushinsai:{name:'空芯菜',variety:'空芯菜',emoji:'🥬',place:'5畝目',stage:'生育中',progress:46,outlook:'草丈が伸びれば順次収穫',caution:'乾燥させすぎない',harvest:0,unit:'回'}
};
const state={route:'home',history:[],selectedCrop:'tomato',recordDraft:{crop:'tomato',types:['harvest'],count:1,memo:'',photo:''},selectedRecord:null,records:read(STORAGE.records,defaultRecords),todos:read(STORAGE.todos,[{id:1,title:'スイカの実と保護カゴを見る',note:'食害と接地面を確認',done:false},{id:2,title:'熟したトマトを収穫する',note:'赤い実だけ',done:false}])};
const $=s=>document.querySelector(s),main=$('#main'),header=$('#appHeader'),tabbar=$('#tabbar');
function read(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):structuredClone(f)}catch{return structuredClone(f)}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function iconCamera(){return `<svg viewBox="0 0 24 24"><path d="M14.5 5 13 3h-2L9.5 5H5a2 2 0 0 0-2 2v11h18V7a2 2 0 0 0-2-2Z"/><circle cx="12" cy="12" r="4"/></svg>`}
function init(){setTimeout(()=>{const s=$('#splash');s.style.opacity=0;setTimeout(()=>s.remove(),360);header.classList.remove('hidden');main.classList.remove('hidden');tabbar.classList.remove('hidden');render()},430);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>navigate(b.dataset.tab,true));$('#settingsButton').onclick=()=>navigate('settings');$('#backButton').onclick=back}
function navigate(route,root=false,data={}){if(!root)state.history.push(state.route);else state.history=[];state.route=route;Object.assign(state,data);window.scrollTo({top:0,behavior:'instant'});render()}
function back(){state.route=state.history.pop()||'home';render()}
function title(r){return({home:'Home',crops:'栽培',cropDetail:'栽培',records:'記録',recordNew:'今日の記録',recordDetail:'記録',library:'図鑑',libraryCrop:'育った物語',settings:'設定',aiSettings:'AI設定',privacy:'データとプライバシー',appearance:'表示'})[r]||''}
function render(){const root=['home','crops','records','library'].includes(state.route);$('#pageTitle').textContent=title(state.route);$('#backButton').classList.toggle('hidden',root);$('#settingsButton').classList.toggle('hidden',state.route!=='home');tabbar.classList.toggle('hidden',!root);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.route));const fn={home:renderHome,crops:renderCrops,cropDetail:renderCropDetail,records:renderRecords,recordNew:renderRecordNew,recordDetail:renderRecordDetail,library:renderLibrary,libraryCrop:renderLibraryCrop,settings:renderSettings,aiSettings:renderAISettings,privacy:renderPrivacy,appearance:renderAppearance}[state.route];fn()}
function renderHome(){const undone=state.todos.filter(t=>!t.done);main.innerHTML=`
  <section class="greeting"><h2>おはようございます。</h2><p>今日の畑には、小さな楽しみが待っています。</p></section>
  <section class="hero-card">
    <div class="hero-scene"><span class="sun"></span><span class="hill one"></span><span class="hill two"></span><span class="plant p1"></span><span class="plant p2"></span><span class="plant p3"></span><span class="tomato t1"></span><span class="tomato t2"></span><span class="tomato t3"></span></div>
    <div class="hero-copy"><span class="hero-label">🌱 今日の畑から</span><h3>トマトが、また少し赤くなっています。</h3><p>朝の涼しいうちに、実の色を見に行くのが楽しみです。</p></div>
  </section>
  <div class="section-title"><h2>今日の楽しみ</h2><p>見るだけでも大丈夫</p></div>
  <section class="enjoy-grid">
    <button class="enjoy-card" data-crop="tomato"><span class="emoji">🍅</span><strong>トマトの収穫</strong><span>赤く熟した実を探す</span></button>
    <button class="enjoy-card" data-crop="watermelon"><span class="emoji">🍉</span><strong>スイカの確認</strong><span>収穫まであと少し</span></button>
  </section>
  <div class="section-title"><h2>今日やること</h2><p>${undone.length}件</p></div>
  <section class="card todo-card">${state.todos.map(t=>`<label class="todo"><input type="checkbox" data-todo="${t.id}" ${t.done?'checked':''}><span><strong>${esc(t.title)}</strong><span>${esc(t.note)}</span></span></label>`).join('')}</section>
  <div class="section-title"><h2>今日を残す</h2><p>15秒で記録</p></div>
  <button id="quickRecord" class="quick-record"><span class="round-icon">${iconCamera()}</span><span><strong>今日の記録を残す</strong><small>収穫・作業・写真・メモ</small></span><span class="chev">›</span></button>`;
  main.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>navigate('cropDetail',false,{selectedCrop:b.dataset.crop}));
  main.querySelectorAll('[data-todo]').forEach(i=>i.onchange=()=>{const t=state.todos.find(x=>String(x.id)===i.dataset.todo);t.done=i.checked;write(STORAGE.todos,state.todos);toast(i.checked?'できました。おつかれさまです':'未完了に戻しました')});
  $('#quickRecord').onclick=()=>startRecord();
}
function renderCrops(){main.innerHTML=`<section class="greeting"><h2>今、どんな状態？</h2><p>数字より先に、現在の段階と次の見通しを見ます。</p></section><section class="crop-list">${Object.entries(crops).map(([id,c])=>`<button class="crop-row" data-crop="${id}"><span class="crop-visual">${c.emoji}</span><span><span class="stage">${c.stage}</span><h3>${c.name}</h3><p>${c.variety}・${c.place}</p><span class="crop-progress"><i style="width:${c.progress}%"></i></span></span><span class="chev">›</span></button>`).join('')}</section>`;main.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>navigate('cropDetail',false,{selectedCrop:b.dataset.crop}))}
function renderCropDetail(){const c=crops[state.selectedCrop];const total=c.harvest+state.records.filter(r=>r.crop===state.selectedCrop&&r.types.includes('harvest')&&r.id>10).reduce((s,r)=>s+(r.count||0),0);main.innerHTML=`<section class="card detail-hero"><div class="big-emoji">${c.emoji}</div><span class="stage">${c.stage}</span><h2>${c.name}</h2><p>${c.variety}・${c.place}</p><div class="progress-ring" style="--progress:${c.progress*3.6}deg"><div><strong>${c.progress}%</strong><small>今季の目安</small></div></div><dl class="fact-grid"><div class="fact"><dt>現在</dt><dd>${c.stage}</dd></div><div class="fact"><dt>これから</dt><dd>${c.outlook}</dd></div><div class="fact full"><dt>注意</dt><dd>${c.caution}</dd></div></dl></section><section class="card harvest-total"><span>累計収穫</span><strong>${total}${c.unit}</strong><small>今季の記録</small></section><div class="button-stack"><button id="recordCrop" class="primary full">この作物を記録する</button><button id="storyCrop" class="secondary full">育った物語を見る</button></div>`;$('#recordCrop').onclick=()=>startRecord(state.selectedCrop);$('#storyCrop').onclick=()=>navigate('libraryCrop',false,{selectedCrop:state.selectedCrop})}
function renderRecords(){main.innerHTML=`<section class="greeting"><h2>何をやった？</h2><p>作業、収穫、写真、気づきを時間の順に残します。</p></section><button id="newRecord" class="quick-record"><span class="round-icon">${iconCamera()}</span><span><strong>今日の記録を残す</strong><small>畑での発見も記録できます</small></span><span class="chev">›</span></button><div class="section-title"><h2>最近の記録</h2><p>${state.records.length}件</p></div><section class="record-list">${state.records.length?state.records.map(r=>recordRow(r)).join(''):`<div class="card empty"><div class="emoji">📝</div><h3>まだ記録がありません</h3><p>収穫だけでなく、花が咲いた日や虫を見つけた日も、大切な記録です。</p></div>`}</section>`;$('#newRecord').onclick=()=>startRecord();main.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>navigate('recordDetail',false,{selectedRecord:state.records.find(r=>String(r.id)===b.dataset.record)}))}
function recordRow(r){const c=crops[r.crop]||{emoji:'🌱',name:'農園'};const label=r.types.includes('harvest')?`${c.name}を${r.count}${c.unit||'個'}収穫`:r.types.includes('work')?`${c.name}の作業`:`${c.name}を観察`;return `<button class="record-item" data-record="${r.id}"><span class="record-thumb">${r.photo?`<img src="${r.photo}" alt="記録写真">`:c.emoji}</span><span><time>${r.date}</time><h3>${label}</h3><p>${esc(r.memo||'今日の記録を残しました')}</p></span><span>›</span></button>`}
function startRecord(crop='tomato'){state.recordDraft={crop,types:['harvest'],count:1,memo:'',photo:''};navigate('recordNew')}
function renderRecordNew(){const d=state.recordDraft;main.innerHTML=`<section class="card form-card"><h2>今日は何を残しますか？</h2><div class="field"><label>記録の種類</label><div class="choice-grid">${[['harvest','🍅','収穫'],['work','🧤','作業'],['observe','✨','発見']].map(x=>`<button class="choice ${d.types.includes(x[0])?'selected':''}" data-type="${x[0]}"><span>${x[1]}</span><strong>${x[2]}</strong></button>`).join('')}</div></div><div class="field"><label>作物</label><select id="cropSelect">${Object.entries(crops).map(([id,c])=>`<option value="${id}" ${d.crop===id?'selected':''}>${c.emoji} ${c.name}</option>`).join('')}</select></div><div class="field ${d.types.includes('harvest')?'':'hidden'}" id="countField"><label>収穫数</label><div class="counter"><button id="minus">−</button><strong id="count">${d.count}</strong><button id="plus">＋</button></div></div><div class="field"><label>写真（任意）</label><label class="photo-picker"><input id="photoInput" type="file" accept="image/*" capture="environment"><span>${d.photo?'写真を変更する':'📷 写真を撮る・選ぶ'}</span></label>${d.photo?`<div class="photo-preview"><img src="${d.photo}" alt="選択した写真"></div>`:''}</div><div class="field"><label>一言メモ（任意）</label><textarea id="memo" placeholder="例：今年初めて花が咲いた">${esc(d.memo)}</textarea></div></section><div class="save-bar"><button id="saveRecord" class="primary full">今日の記録を保存</button></div>`;
  main.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{d.types=[b.dataset.type];d.memo=$('#memo').value;d.crop=$('#cropSelect').value;renderRecordNew()});
  $('#cropSelect').onchange=e=>d.crop=e.target.value;
  if($('#minus'))$('#minus').onclick=()=>{$('#count').textContent=d.count=Math.max(1,d.count-1)};
  if($('#plus'))$('#plus').onclick=()=>{$('#count').textContent=++d.count};
  $('#memo').oninput=e=>d.memo=e.target.value;
  $('#photoInput').onchange=e=>compress(e.target.files[0],data=>{d.photo=data;renderRecordNew()});
  $('#saveRecord').onclick=saveRecord;
}
function saveRecord(){const d=state.recordDraft,now=new Date(),type=d.types[0];state.records.unshift({id:Date.now(),date:`${now.getMonth()+1}月${now.getDate()}日`,iso:now.toISOString().slice(0,10),crop:d.crop,types:[type],count:type==='harvest'?d.count:0,memo:$('#memo').value.trim(),photo:d.photo});write(STORAGE.records,state.records);renderDone()}
function renderDone(){const d=state.recordDraft,c=crops[d.crop];tabbar.classList.add('hidden');$('#backButton').classList.add('hidden');main.innerHTML=`<section class="done-screen"><div class="leaf">🌱</div><h2>今日も、<br>ありがとうございました。</h2><p>畑で過ごした時間を、記録に残しました。</p><div class="done-summary"><strong>${c.emoji} ${c.name}</strong><p>${d.types.includes('harvest')?`${d.count}${c.unit}を収穫`:(d.types.includes('work')?'作業を記録':'今日の発見を記録')}</p></div><button id="finishRecord" class="primary full">記録を見る</button></section>`;$('#finishRecord').onclick=()=>navigate('records',true)}
function renderRecordDetail(){const r=state.selectedRecord,c=crops[r.crop];main.innerHTML=`<section class="card form-card"><span class="stage">${r.date}</span><h2 style="margin-top:12px">${c.emoji} ${c.name}</h2>${r.photo?`<div class="photo-preview"><img src="${r.photo}" alt="記録写真"></div>`:''}<dl class="fact-grid" style="margin-top:18px"><div class="fact"><dt>種類</dt><dd>${r.types.includes('harvest')?'収穫':r.types.includes('work')?'作業':'発見'}</dd></div><div class="fact"><dt>数量</dt><dd>${r.types.includes('harvest')?`${r.count}${c.unit}`:'—'}</dd></div><div class="fact full"><dt>メモ</dt><dd>${esc(r.memo||'メモはありません')}</dd></div></dl><div class="button-stack"><button id="deleteRecord" class="danger full">この記録を削除</button></div></section>`;$('#deleteRecord').onclick=()=>{if(confirm('この記録を削除しますか？')){state.records=state.records.filter(x=>x.id!==r.id);write(STORAGE.records,state.records);navigate('records',true);toast('記録を削除しました')}}}
function renderLibrary(){main.innerHTML=`<section class="card library-cover"><div class="cover-art"><span class="book-emoji">📖</span></div><div class="cover-copy"><span>TANY FARM STORY</span><h2>育った物語</h2><p>野菜の成長、写真、収穫、学びが、少しずつ自分たちだけの図鑑になります。</p></div></section><div class="section-title"><h2>今季の作物</h2><p>${Object.keys(crops).length}種類</p></div><section class="library-grid">${Object.entries(crops).map(([id,c])=>`<button class="library-card" data-library="${id}"><span class="emoji">${c.emoji}</span><h3>${c.name}</h3><p>${c.harvest}${c.unit}の収穫記録<br>${c.stage}</p></button>`).join('')}</section>`;main.querySelectorAll('[data-library]').forEach(b=>b.onclick=()=>navigate('libraryCrop',false,{selectedCrop:b.dataset.library}))}
function renderLibraryCrop(){const c=crops[state.selectedCrop],records=state.records.filter(r=>r.crop===state.selectedCrop);main.innerHTML=`<section class="card detail-hero"><div class="big-emoji">${c.emoji}</div><span class="stage">2026年</span><h2>${c.name}</h2><p>${c.variety}</p></section><section class="card"><dl class="fact-grid"><div class="fact"><dt>栽培場所</dt><dd>${c.place}</dd></div><div class="fact"><dt>現在</dt><dd>${c.stage}</dd></div><div class="fact"><dt>累計収穫</dt><dd>${c.harvest}${c.unit}</dd></div><div class="fact"><dt>記録</dt><dd>${records.length}件</dd></div><div class="fact full"><dt>今年の学び</dt><dd>${c.caution}</dd></div></dl></section><div class="section-title"><h2>成長の記録</h2><p>${records.length}件</p></div><section class="record-list">${records.length?records.map(recordRow).join(''):`<div class="card empty"><div class="emoji">🌿</div><h3>これから育つ物語</h3><p>この作物の記録を残すと、ここに並びます。</p></div>`}</section>`;main.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>navigate('recordDetail',false,{selectedRecord:state.records.find(r=>String(r.id)===b.dataset.record)}))}
function renderSettings(){main.innerHTML=`<section class="card"><div class="settings-group"><button class="setting-row" data-settings="aiSettings"><span><strong>AI設定</strong><span>AIが使う情報と、案内の仕方</span></span><span class="chev">›</span></button><button class="setting-row" data-settings="privacy"><span><strong>データとプライバシー</strong><span>保存場所、共有、削除について</span></span><span class="chev">›</span></button><button class="setting-row" data-settings="appearance"><span><strong>表示</strong><span>文字や季節の演出</span></span><span class="chev">›</span></button></div></section><section class="card" style="margin-top:14px"><p class="privacy-note">このデモの記録と写真は、現在使っている端末のブラウザ内だけに保存されます。外部送信や夫婦間同期は行いません。</p><button id="resetData" class="danger full">テストデータを初期化</button></section>`;main.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>navigate(b.dataset.settings));$('#resetData').onclick=()=>{if(confirm('記録とチェック状態を初期状態に戻しますか？')){localStorage.removeItem(STORAGE.records);localStorage.removeItem(STORAGE.todos);state.records=structuredClone(defaultRecords);state.todos=[{id:1,title:'スイカの実と保護カゴを見る',note:'食害と接地面を確認',done:false},{id:2,title:'熟したトマトを収穫する',note:'赤い実だけ',done:false}];toast('初期状態に戻しました')}}}
function renderAISettings(){main.innerHTML=`<section class="card form-card"><h2>AIは、静かな相棒です。</h2><p class="privacy-note">命令したり、不安をあおったりせず、記録や天気をもとに短い提案をします。判断するのは、いつも人です。</p><dl class="fact-grid" style="margin-top:16px"><div class="fact full"><dt>使う情報</dt><dd>作物、栽培段階、過去の記録、必要に応じて天気</dd></div><div class="fact full"><dt>使わない情報</dt><dd>連絡先、位置情報、他のアプリの内容</dd></div><div class="fact full"><dt>言葉の方針</dt><dd>短く、やさしく、根拠を示し、最終判断を任せる</dd></div></dl></section>`}
function renderPrivacy(){main.innerHTML=`<section class="card form-card"><h2>データの扱い</h2><dl class="fact-grid"><div class="fact full"><dt>現在の保存場所</dt><dd>この端末のブラウザ内</dd></div><div class="fact full"><dt>外部送信</dt><dd>このデモでは行いません</dd></div><div class="fact full"><dt>共有・同期</dt><dd>まだありません</dd></div><div class="fact full"><dt>削除</dt><dd>設定画面の「テストデータを初期化」から削除できます</dd></div></dl></section>`}
function renderAppearance(){main.innerHTML=`<section class="card form-card"><h2>表示</h2><div class="settings-group"><div class="setting-row"><span><strong>季節の空気</strong><span>春・夏・秋・冬でHomeの言葉と景色を変える</span></span><span>夏</span></div><div class="setting-row"><span><strong>文字サイズ</strong><span>畑でも読みやすい標準サイズ</span></span><span>標準</span></div><div class="setting-row"><span><strong>動き</strong><span>控えめなアニメーション</span></span><span>ON</span></div></div></section>`}
function compress(file,done){if(!file)return;const r=new FileReader();r.onerror=()=>toast('写真を読み込めませんでした');r.onload=()=>{const img=new Image();img.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);done(c.toDataURL('image/jpeg',.74))};img.src=r.result};r.readAsDataURL(file)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
