const STORAGE={tasks:'tanyV8Tasks',journal:'tanyV8Journal'};
const state={route:'home',history:[],selectedCrop:'tomato',harvestCount:1,harvestPhoto:'',editingTask:null,selectedJournal:null,tasks:read(STORAGE.tasks,[]),journal:read(STORAGE.journal,[])};
const crops={
 tomato:{name:'ミニトマト',variety:'アイコ',emoji:'🍅',status:'収穫中',place:'3畝目',last:'7月21日',next:'熟した実と葉の状態を確認'},
 watermelon:{name:'小玉スイカ',variety:'品種不明',emoji:'🍉',status:'実を育てている',place:'2畝目',last:'7月20日',next:'実・つる・保護カゴを確認'},
 pepper:{name:'ピーマン',variety:'品種未登録',emoji:'🫑',status:'収穫中',place:'4畝目',last:'7月21日',next:'実の大きさと株の元気を確認'},
 basil:{name:'バジル',variety:'スイートバジル',emoji:'🌿',status:'収穫中',place:'1・3・4畝目',last:'7月17日',next:'花芽と葉の量を確認'},
 shiso:{name:'青じそ',variety:'青じそ',emoji:'🌱',status:'収穫中',place:'1畝目',last:'7月17日',next:'大きな葉から収穫'},
 kushinsai:{name:'空芯菜',variety:'空芯菜',emoji:'🥬',status:'生育中',place:'5畝目',last:'未記録',next:'草丈と新芽を確認'}
};
const suggestions=[
 {id:'s1',title:'スイカの実と保護カゴを確認',reason:'前回の確認から日数が空いています。食害と接地面を見ましょう。'},
 {id:'s2',title:'乾いている株だけ水やり',reason:'天気だけで決めず、土と葉の状態を見て判断しましょう。'}
];
const $=s=>document.querySelector(s),main=$('#main'),header=$('#appHeader'),tabbar=$('#tabbar');
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mascot(cls=''){return `<div class="mascot-v6 ${cls}" aria-label="tany仮キャラクター"><svg viewBox="0 0 120 120"><path d="M58 34 C50 18 34 14 23 22 C31 37 43 43 58 42" fill="#6f9168"/><path d="M61 33 C68 16 84 13 97 22 C90 37 76 43 61 42" fill="#86a978"/><path d="M60 39 C61 31 62 25 66 18" stroke="#55705a" stroke-width="5" stroke-linecap="round"/><circle cx="60" cy="70" r="35" fill="#fff9ec" stroke="#d9cdbb" stroke-width="3"/><circle cx="48" cy="67" r="4" fill="#4b4339"/><circle cx="72" cy="67" r="4" fill="#4b4339"/><path d="M48 81 Q60 91 72 81" fill="none" stroke="#4b4339" stroke-width="4" stroke-linecap="round"/></svg><span>仮キャラ</span></div>`}
function basketIcon(){return `<span class="basket-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M10 20h28l-3 18H13z" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><path d="M16 20c1-7 5-11 8-11s7 4 8 11" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M18 26v6M24 26v6M30 26v6" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M29 11c4-4 8-3 10-1-3 4-6 5-10 4" fill="currentColor"/></svg></span>`}
function init(){setTimeout(()=>{const s=$('#splash');if(s){s.style.opacity=0;setTimeout(()=>s.remove(),300)}header.classList.remove('hidden');main.classList.remove('hidden');tabbar.classList.remove('hidden');render()},350);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>navigate(b.dataset.tab,true));$('#settingsButton').onclick=()=>navigate('settings');$('#backButton').onclick=goBack}
function navigate(route,root=false,data={}){if(!root)state.history.push(state.route);else state.history=[];state.route=route;Object.assign(state,data);scrollTo(0,0);render()}
function goBack(){state.route=state.history.pop()||'home';render()}
function titleFor(r){return({home:'Home',crops:'栽培',cropDetail:'栽培詳細',harvest:'収穫入力',footprint:'足あと',journal:'日誌',journalDetail:'日誌詳細',journalEdit:'日誌編集',library:'図鑑',settings:'設定',taskEdit:'作業を編集'})[r]||''}
function render(){const root=['home','crops','journal','library'].includes(state.route);$('#pageTitle').textContent=titleFor(state.route);$('#backButton').classList.toggle('hidden',root);$('#settingsButton').classList.toggle('hidden',state.route!=='home');tabbar.classList.toggle('hidden',!root);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.route));({home:renderHome,crops:renderCrops,cropDetail:renderCropDetail,harvest:renderHarvest,footprint:renderFootprint,journal:renderJournal,journalDetail:renderJournalDetail,journalEdit:renderJournalEdit,library:renderLibrary,settings:renderSettings,taskEdit:renderTaskEdit})[state.route]()}
function renderHome(){const adopted=state.tasks.filter(t=>t.status==='today');main.innerHTML=`<section class="review-banner"><b>v8 実使用テスト版</b><span>記録・写真・日誌を保存</span></section><section class="greeting"><h2>おはようございます</h2><p>提案を見て、今日することを自分たちで決めます。</p></section><section class="card tany-card"><div class="tany-head">${mascot()}<div class="tany-copy"><span class="badge">tanyから</span><h2>朝の涼しいうちに畑を見よう</h2><p>提案は未確定です。採用・編集・見送りを選べます。</p></div></div><div class="today-status"><div class="status-pill"><b>晴れ・31℃</b><span>デモ天気</span></div><div class="status-pill"><b>収穫 5種</b><span>作物を選択</span></div><div class="status-pill"><b>今日 ${adopted.length}件</b><span>自分で管理</span></div></div></section><button id="quickHarvest" class="quick-action">${basketIcon()}<span><strong>収穫を記録する</strong><small>作物・数量・写真を保存</small></span><span class="arrow">›</span></button><div class="section-head"><h2>tanyの提案</h2><span class="tiny muted">未確定</span></div><section class="suggestion-list">${suggestions.map(s=>`<article class="card suggestion-card"><div><span class="ai-label">提案・未保存</span><h3>${s.title}</h3><p>${s.reason}</p></div><div class="suggestion-actions"><button class="ghost small-btn" data-skip="${s.id}">今回はしない</button><button class="ghost small-btn" data-edit="${s.id}">編集</button><button class="primary small-btn" data-adopt="${s.id}">今日やる</button></div></article>`).join('')}</section><div class="section-head"><h2>今日やること</h2><button id="addTask" class="text-button">＋追加</button></div><section class="card task-card">${adopted.length?adopted.map(t=>`<label class="task"><input type="checkbox" data-id="${t.id}" ${t.done?'checked':''}><span><strong>${esc(t.title)}</strong><span>${esc(t.note||'自分たちで決めた作業')}</span></span><button class="task-edit" data-task="${t.id}">編集</button></label>`).join(''):'<p class="muted tiny empty-note">まだありません。提案を採用するか、自分で追加できます。</p>'}</section>`;
$('#quickHarvest').onclick=()=>navigate('harvest',false,{harvestPhoto:'',harvestCount:1});$('#addTask').onclick=()=>navigate('taskEdit',false,{editingTask:null});main.querySelectorAll('[data-adopt]').forEach(b=>b.onclick=()=>{const s=suggestions.find(x=>x.id===b.dataset.adopt);state.tasks.push({id:Date.now(),title:s.title,note:s.reason,status:'today',done:false});write(STORAGE.tasks,state.tasks);renderHome();toast('今日やることに追加しました')});main.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>toast('今回は見送りました'));main.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const s=suggestions.find(x=>x.id===b.dataset.edit);navigate('taskEdit',false,{editingTask:{title:s.title,note:s.reason}})});main.querySelectorAll('[data-id]').forEach(el=>el.onchange=()=>{const t=state.tasks.find(x=>String(x.id)===el.dataset.id);if(t)t.done=el.checked;write(STORAGE.tasks,state.tasks);renderHome()});main.querySelectorAll('[data-task]').forEach(b=>b.onclick=e=>{e.preventDefault();navigate('taskEdit',false,{editingTask:state.tasks.find(x=>String(x.id)===b.dataset.task)})})}
function renderTaskEdit(){const t=state.editingTask||{};main.innerHTML=`<section class="card"><h2>${t.id?'作業を編集':'作業を追加・調整'}</h2><div class="form-group"><label>作業名</label><input id="taskTitle" value="${esc(t.title||'')}" placeholder="例：ピーマンを収穫"></div><div class="form-group"><label>判断メモ</label><textarea id="taskNote" placeholder="理由や注意点">${esc(t.note||'')}</textarea></div><p class="notice">提案はそのまま確定せず、内容を確認・編集して保存します。</p></section><div class="modal-actions"><button id="saveTask" class="primary full">今日やることに保存</button></div>`;$('#saveTask').onclick=()=>{const item={id:t.id||Date.now(),title:$('#taskTitle').value.trim()||'名称未設定の作業',note:$('#taskNote').value.trim(),status:'today',done:t.done||false};const i=state.tasks.findIndex(x=>x.id===item.id);if(i>=0)state.tasks[i]=item;else state.tasks.push(item);write(STORAGE.tasks,state.tasks);navigate('home',true);toast('作業を保存しました')}}
function cropImage(c){const latest=state.journal.find(j=>j.crop&&crops[j.crop]?.name===c.name&&j.photo);return latest?`<img src="${latest.photo}" alt="${c.name}の記録写真">`:`<span class="crop-emoji">${c.emoji}</span><span class="photo-label">写真未登録</span>`}
function renderCrops(){main.innerHTML=`<p class="muted tiny">「何％進んだか」ではなく、今の段階と次に見ることを表示します。</p><div class="crop-grid">${Object.entries(crops).map(([id,c])=>`<button class="crop-card" data-crop="${id}"><div class="crop-photo">${cropImage(c)}</div><div class="crop-body"><span class="badge">${c.status}</span><h3>${c.name}</h3><p>${c.variety}・${c.place}</p><dl class="crop-next"><div><dt>前回の記録</dt><dd>${c.last}</dd></div><div><dt>次の目安</dt><dd>${c.next}</dd></div></dl></div></button>`).join('')}</div>`;main.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>navigate('cropDetail',false,{selectedCrop:b.dataset.crop}))}
function renderCropDetail(){const c=crops[state.selectedCrop],records=state.journal.filter(j=>j.crop===state.selectedCrop);main.innerHTML=`<section class="card detail-hero"><div class="detail-emoji">${c.emoji}</div><span class="badge">${c.status}</span><h2>${c.name}</h2><p>${c.variety}・${c.place}</p><dl class="crop-next"><div><dt>前回の記録</dt><dd>${c.last}</dd></div><div><dt>次の目安</dt><dd>${c.next}</dd></div></dl></section><section class="card"><div class="section-head"><h2>最近の記録</h2><span class="tiny muted">${records.length}件</span></div>${records.length?`<div class="mini-gallery">${records.slice(0,6).map(r=>r.photo?`<img src="${r.photo}" alt="記録写真">`:`<div>${c.emoji}</div>`).join('')}</div>`:'<p class="muted tiny">まだ記録がありません。</p>'}</section><button id="addHarvest" class="primary full">＋ 収穫を記録</button>`;$('#addHarvest').onclick=()=>navigate('harvest',false,{harvestPhoto:'',harvestCount:1})}
function renderHarvest(){main.innerHTML=`<section class="card"><h2>収穫する作物を選ぶ</h2><div class="harvest-crop-list">${Object.entries(crops).filter(([id])=>id!=='watermelon').map(([id,c])=>`<button class="harvest-crop ${state.selectedCrop===id?'selected':''}" data-hcrop="${id}"><span>${c.emoji}</span><strong>${c.name}</strong></button>`).join('')}</div><div class="form-group"><label>数量</label><div class="counter"><button id="minus">−</button><strong id="count">${state.harvestCount}</strong><button id="plus">＋</button></div></div><div class="form-group"><label>写真（任意）</label><label class="photo-picker"><input id="photoInput" type="file" accept="image/*" capture="environment"><span>${state.harvestPhoto?'写真を変更':'写真を撮る・選ぶ'}</span></label><div id="photoPreview" class="photo-preview">${state.harvestPhoto?`<img src="${state.harvestPhoto}" alt="選択した写真">`:'<span>写真はこのiPhone内に保存されます</span>'}</div></div><div class="form-group"><label>メモ（任意）</label><input id="harvestMemo" placeholder="例：よく熟していた"></div></section><div class="modal-actions"><button id="saveHarvest" class="primary full">収穫を保存</button></div>`;main.querySelectorAll('[data-hcrop]').forEach(b=>b.onclick=()=>{state.selectedCrop=b.dataset.hcrop;renderHarvest()});$('#minus').onclick=()=>{$('#count').textContent=state.harvestCount=Math.max(1,state.harvestCount-1)};$('#plus').onclick=()=>{$('#count').textContent=++state.harvestCount};$('#photoInput').onchange=e=>compressImage(e.target.files[0],data=>{state.harvestPhoto=data;renderHarvest()});$('#saveHarvest').onclick=()=>{const now=new Date();state.journal.unshift({id:Date.now(),crop:state.selectedCrop,count:state.harvestCount,memo:$('#harvestMemo').value.trim(),date:`${now.getMonth()+1}月${now.getDate()}日`,photo:state.harvestPhoto,footprint:''});write(STORAGE.journal,state.journal);navigate('footprint')}}
function compressImage(file,done){if(!file)return;const r=new FileReader();r.onerror=()=>toast('写真を読み込めませんでした');r.onload=()=>{const img=new Image();img.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);done(c.toDataURL('image/jpeg',.72))};img.src=r.result};r.readAsDataURL(file)}
function renderFootprint(){main.innerHTML=`<section class="card"><div class="tany-head">${mascot('small')}<div><h2>足あとを添えますか？</h2><p class="tiny muted">任意です。収穫記録はすでに保存されています。</p></div></div><div class="form-group"><label>一言</label><textarea id="footText" placeholder="例：妻と一緒に収穫できた"></textarea></div></section><div class="button-row modal-actions"><button id="skipFoot" class="ghost">追加しない</button><button id="saveFoot" class="primary">保存</button></div>`;$('#skipFoot').onclick=()=>navigate('journal',true);$('#saveFoot').onclick=()=>{if(state.journal[0])state.journal[0].footprint=$('#footText').value.trim();write(STORAGE.journal,state.journal);navigate('journal',true)}}
function renderJournal(){main.innerHTML=`<div class="section-head"><h2>農園の日誌</h2><button class="text-button" id="newJournal">＋記録</button></div><p class="muted tiny">収穫記録は自動で日誌にまとまります。</p><div class="journal-list">${state.journal.length?state.journal.map(r=>`<button class="card journal-item" data-journal="${r.id}"><div class="journal-thumb">${r.photo?`<img src="${r.photo}" alt="記録写真">`:crops[r.crop]?.emoji||'📝'}</div><div><span class="tiny muted">${r.date}</span><h3>${crops[r.crop]?.name||'農園記録'}を${r.count||''}${r.count?'収穫':''}</h3><p>${esc(r.memo||r.footprint||'収穫を記録しました')}</p></div><span>›</span></button>`).join(''):'<section class="card empty-state"><h3>まだ日誌がありません</h3><p>収穫を記録すると、ここに自動で残ります。</p></section>'}</div>`;main.querySelectorAll('[data-journal]').forEach(b=>b.onclick=()=>navigate('journalDetail',false,{selectedJournal:state.journal.find(r=>String(r.id)===b.dataset.journal)}));$('#newJournal').onclick=()=>navigate('harvest')}
function renderJournalDetail(){const r=state.selectedJournal,c=crops[r.crop];main.innerHTML=`<section class="card"><span class="tiny muted">${r.date}</span><h2>${c?.name||'農園記録'}</h2>${r.photo?`<img class="journal-photo" src="${r.photo}" alt="${c?.name||'農園'}の写真">`:`<div class="photo-placeholder large">${c?.emoji||'📝'}<strong>写真なし</strong></div>`}<dl class="record-details"><div><dt>数量</dt><dd>${r.count||'未入力'}</dd></div><div><dt>メモ</dt><dd>${esc(r.memo||'なし')}</dd></div><div><dt>足あと</dt><dd>${esc(r.footprint||'なし')}</dd></div></dl><button class="ghost full" id="editJournal">この記録を編集</button><button class="danger-text full" id="deleteJournal">この記録を削除</button></section>`;$('#editJournal').onclick=()=>navigate('journalEdit');$('#deleteJournal').onclick=()=>{if(confirm('この記録を削除しますか？')){state.journal=state.journal.filter(x=>x.id!==r.id);write(STORAGE.journal,state.journal);navigate('journal',true)}}}
function renderJournalEdit(){const r=state.selectedJournal;main.innerHTML=`<section class="card"><h2>日誌を編集</h2><div class="form-group"><label>数量</label><input id="editCount" type="number" min="1" value="${r.count||1}"></div><div class="form-group"><label>メモ</label><textarea id="editMemo">${esc(r.memo||'')}</textarea></div><div class="form-group"><label>足あと</label><textarea id="editFoot">${esc(r.footprint||'')}</textarea></div></section><div class="modal-actions"><button id="saveJournalEdit" class="primary full">変更を保存</button></div>`;$('#saveJournalEdit').onclick=()=>{r.count=Math.max(1,+$('#editCount').value||1);r.memo=$('#editMemo').value.trim();r.footprint=$('#editFoot').value.trim();write(STORAGE.journal,state.journal);navigate('journalDetail',false,{selectedJournal:r});toast('変更を保存しました')}}
function renderLibrary(){main.innerHTML=`<section class="card"><h2>図鑑は準備中です</h2><p>次の段階で、作物別の育て方と自分たちの記録をつなげます。</p></section>`}
function renderSettings(){main.innerHTML=`<section class="card"><h2>表示と案内役</h2><div class="setting-row"><div><strong>tanyキャラクター</strong><span>正式イラストへいつでも差し替え可能</span></div><div class="toggle on"></div></div><div class="setting-row"><div><strong>天気連携</strong><span>現在は固定のデモデータ</span></div><div class="toggle"></div></div></section><section class="card"><h2>保存について</h2><p class="tiny muted">v8の記録と写真は、この端末のSafari内に保存されます。別端末との共有・バックアップはまだありません。</p><button id="clearData" class="danger-text full">テストデータをすべて削除</button></section>`;$('#clearData').onclick=()=>{if(confirm('v8で保存した作業・日誌・写真を削除しますか？')){localStorage.removeItem(STORAGE.tasks);localStorage.removeItem(STORAGE.journal);state.tasks=[];state.journal=[];toast('テストデータを削除しました')}}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
